version: 0.2

env:
  shell: bash
  variables:
    ECR_REPO: nexus-site
    CONTAINER_NAME: site

phases:
  pre_build:
    commands:
      - echo "=== Pre-build ==="
      - |
        echo "Logging in to Amazon ECR ..."
        aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
        REPOSITORY_URI=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$ECR_REPO
        echo "ECR repository: $REPOSITORY_URI"
      - |
        echo "Running gitleaks ..."
        docker run -v $CODEBUILD_SRC_DIR:/path public.ecr.aws/b2j5x6d3/gitleaks:latest git -v --config /path/.gitleaks.toml --log-opts "-n 1" /path
        echo "Gitleaks passed."

  build:
    commands:
      - |
        echo "=== Build started on $(date) ==="
        echo "Building Docker image ..."
        docker build -t $REPOSITORY_URI:latest .
        echo "=== Build finished on $(date) ==="

  post_build:
    commands:
      - |
        echo "=== Post-build ==="
        echo "Pushing Docker image ..."
        docker push $REPOSITORY_URI:latest
        echo "Writing image definitions file ..."
        printf '[{"name":"%s","imageUri":"%s"}]' $CONTAINER_NAME $REPOSITORY_URI:latest > imagedefinitions.json
        echo "=== Post-build finished ==="

artifacts:
  files: imagedefinitions.json
