/**
 * gen-api-data.ts
 *
 * Parses a Protobuf FileDescriptorSet (descriptor.json, generated by
 * `buf build -o descriptor.json`) and extracts structured API data
 * including custom options (skip_auth, agent_only, user_only, sensitive)
 * and buf.validate constraints.
 *
 * Prerequisites:
 *   cd ../nexus-ai/proto && buf build --path api/v1 --path shared/v1 -o ../../nexus-site/public/api-data/descriptor.json
 *
 * Usage: pnpm tsx scripts/gen-api-data.ts
 */

/// <reference types="node" />

import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { join } from "node:path";

// ── Output types ──
interface ApiData {
  version: string;
  generatedAt: string;
  services: ServiceInfo[];
  messages: Record<string, MessageInfo>;
  enums: Record<string, EnumInfo>;
}

interface ServiceInfo {
  name: string;
  fullName: string;
  description: string;
  methods: MethodInfo[];
}

interface MethodInfo {
  name: string;
  description: string;
  httpPath: string;
  options: {
    agentOnly: boolean;
    userOnly: boolean;
    skipAuth: boolean;
  };
  inputType: string;
  outputType: string;
}

interface MessageInfo {
  name: string;
  fullName: string;
  description: string;
  fields: FieldInfo[];
}

interface FieldInfo {
  name: string;
  jsonName: string;
  type: string;
  description: string;
  optional: boolean;
  repeated: boolean;
  oneofGroup?: string;
  sensitive: boolean;
  validation?: ValidationInfo;
}

interface ValidationInfo {
  minLen?: number;
  maxLen?: number;
  gt?: number;
  gte?: number;
  lte?: number;
  maxItems?: number;
}

interface EnumInfo {
  name: string;
  fullName: string;
  description: string;
  values: { name: string; number: number; description: string }[];
}

// ── JSON Descriptor types (from buf build JSON output) ──
// eslint-disable-next-line @typescript-eslint/no-explicit-any
type AnyOptions = Record<string, any>;

interface DescriptorFile {
  name: string;
  package?: string;
  messageType?: DescriptorMessage[];
  enumType?: DescriptorEnum[];
  service?: DescriptorService[];
  sourceCodeInfo?: { location: SourceLocation[] };
}

interface DescriptorMessage {
  name: string;
  field?: DescriptorField[];
  nestedType?: DescriptorMessage[];
  enumType?: DescriptorEnum[];
  oneofDecl?: { name: string }[];
  options?: AnyOptions;
}

interface DescriptorField {
  name: string;
  number?: number;
  label?: string;
  type?: string;
  typeName?: string;
  jsonName?: string;
  oneofIndex?: number;
  proto3Optional?: boolean;
  options?: AnyOptions;
}

interface DescriptorEnum {
  name: string;
  value?: { name: string; number?: number; options?: AnyOptions }[];
}

interface DescriptorService {
  name: string;
  method?: DescriptorMethod[];
}

interface DescriptorMethod {
  name: string;
  inputType?: string;
  outputType?: string;
  options?: AnyOptions;
}

interface SourceLocation {
  path?: number[];
  leadingComments?: string;
}

// ── Proto type string to simple name ──
const TYPE_MAP: Record<string, string> = {
  TYPE_DOUBLE: "double",
  TYPE_FLOAT: "float",
  TYPE_INT64: "int64",
  TYPE_UINT64: "uint64",
  TYPE_INT32: "int32",
  TYPE_FIXED64: "fixed64",
  TYPE_FIXED32: "fixed32",
  TYPE_BOOL: "bool",
  TYPE_STRING: "string",
  TYPE_GROUP: "group",
  TYPE_MESSAGE: "message",
  TYPE_BYTES: "bytes",
  TYPE_UINT32: "uint32",
  TYPE_ENUM: "enum",
  TYPE_SFIXED32: "sfixed32",
  TYPE_SFIXED64: "sfixed64",
  TYPE_SINT32: "sint32",
  TYPE_SINT64: "sint64",
};

// ── Source code info helpers ──
// Normalize a protobuf leading comment into clean readable text.
// Protobuf comments use "// " prefix (stripped by protoc), with:
//   - Indented list items: "  - item text" or "    continuation"
//   - Blank lines separating paragraphs
//   - Multi-line continuation via indentation
function normalizeComment(raw: string): string {
  const lines = raw.replace(/\r\n/g, "\n").replace(/\r/g, "\n").split("\n");
  const out: string[] = [];

  for (const line of lines) {
    const content = line.trimEnd();

    // Blank line → paragraph break
    if (content.trim() === "") {
      out.push("");
      continue;
    }

    // Detect list items: lines starting with optional whitespace then "- "
    const listMatch = content.match(/^\s*[-*]\s+(.*)/);
    if (listMatch) {
      out.push(`- ${listMatch[1].trim()}`);
      continue;
    }

    // Indented continuation line (part of a previous list item or paragraph)
    if (/^\s{2,}/.test(content) && out.length > 0) {
      const prev = out[out.length - 1];
      // Append to previous line if it's a list item or non-empty text
      if (prev && prev !== "") {
        out[out.length - 1] = `${prev} ${content.trim()}`;
        continue;
      }
    }

    // Regular line
    out.push(content.trim());
  }

  // Collapse runs of 3+ newlines into 2, then trim
  return out.join("\n").replace(/\n{3,}/g, "\n\n").trim();
}

function buildCommentMap(locations: SourceLocation[]): Map<string, string> {
  const comments = new Map<string, string>();
  for (const loc of locations) {
    if (loc.leadingComments && loc.path) {
      comments.set(loc.path.join("."), normalizeComment(loc.leadingComments));
    }
  }
  return comments;
}

// ── Extract validation constraints from buf.validate options ──
function extractValidation(options: AnyOptions): ValidationInfo | undefined {
  const validate = options?.["[buf.validate.field]"];
  if (!validate) return undefined;

  const validation: ValidationInfo = {};

  if (validate.string) {
    if (validate.string.minLen !== undefined) validation.minLen = Number(validate.string.minLen);
    if (validate.string.maxLen !== undefined) validation.maxLen = Number(validate.string.maxLen);
  }

  for (const numType of ["int32", "int64", "uint32", "uint64"]) {
    const c = validate[numType];
    if (c) {
      if (c.gt !== undefined) validation.gt = Number(c.gt);
      if (c.gte !== undefined) validation.gte = Number(c.gte);
      if (c.lte !== undefined) validation.lte = Number(c.lte);
    }
  }

  if (validate.repeated) {
    if (validate.repeated.maxItems !== undefined) validation.maxItems = Number(validate.repeated.maxItems);
  }

  return Object.keys(validation).length > 0 ? validation : undefined;
}

// ── Extract custom method options ──
function extractMethodOptions(options?: AnyOptions): MethodInfo["options"] {
  if (!options) return { agentOnly: false, userOnly: false, skipAuth: false };
  return {
    skipAuth: options["[shared.v1.skip_auth]"] === true,
    agentOnly: options["[shared.v1.agent_only]"] === true,
    userOnly: options["[shared.v1.user_only]"] === true,
  };
}

// ── Extract sensitive field option ──
function extractSensitive(options?: AnyOptions): boolean {
  if (!options) return false;
  return options["[shared.v1.sensitive]"] === true;
}

// ── Parse a field descriptor ──
function parseField(
  fd: DescriptorField,
  oneofNames: string[],
  comment: string,
): FieldInfo {
  const typeName = fd.typeName ? fd.typeName.replace(/^\./, "") : "";
  const simpleType = fd.type ? TYPE_MAP[fd.type] || fd.type : "unknown";

  return {
    name: fd.name,
    jsonName: fd.jsonName || fd.name,
    type: typeName || simpleType,
    description: comment,
    optional: fd.proto3Optional === true,
    repeated: fd.label === "LABEL_REPEATED",
    oneofGroup: fd.oneofIndex !== undefined ? oneofNames[fd.oneofIndex] : undefined,
    sensitive: extractSensitive(fd.options),
    validation: fd.options ? extractValidation(fd.options) : undefined,
  };
}

// ── Parse a message and its nested types recursively ──
function parseMessage(
  msg: DescriptorMessage,
  pkg: string,
  parentFullName: string,
  comments: Map<string, string>,
  pathPrefix: string,
  messages: Record<string, MessageInfo>,
  enums: Record<string, EnumInfo>,
): void {
  const fullName = parentFullName ? `${parentFullName}.${msg.name}` : `${pkg}.${msg.name}`;
  const msgDesc = comments.get(pathPrefix) || "";
  const oneofNames = (msg.oneofDecl || []).map((o) => o.name);

  const fields: FieldInfo[] = (msg.field || []).map((fd, fieldIdx) => {
    const fieldComment = comments.get(`${pathPrefix}.2.${fieldIdx}`) || "";
    return parseField(fd, oneofNames, fieldComment);
  });

  messages[fullName] = { name: msg.name, fullName, description: msgDesc, fields };

  // Nested messages (field 3 = nested_type in DescriptorProto)
  (msg.nestedType || []).forEach((nested, nestedIdx) => {
    parseMessage(nested, pkg, fullName, comments, `${pathPrefix}.3.${nestedIdx}`, messages, enums);
  });

  // Nested enums (field 4 = enum_type in DescriptorProto)
  (msg.enumType || []).forEach((enumDesc, enumIdx) => {
    const enumFullName = `${fullName}.${enumDesc.name}`;
    const enumComment = comments.get(`${pathPrefix}.4.${enumIdx}`) || "";
    const values = (enumDesc.value || []).map((v, vIdx) => ({
      name: v.name,
      number: v.number || 0,
      description: comments.get(`${pathPrefix}.4.${enumIdx}.2.${vIdx}`) || "",
    }));
    enums[enumFullName] = { name: enumDesc.name, fullName: enumFullName, description: enumComment, values };
  });
}

// ── Main parsing logic ──
function parseDescriptor(descriptorPath: string): ApiData {
  const raw = JSON.parse(readFileSync(descriptorPath, "utf-8"));
  const files: DescriptorFile[] = raw.file || [];

  const services: ServiceInfo[] = [];
  const messages: Record<string, MessageInfo> = {};
  const enums: Record<string, EnumInfo> = {};

  for (const file of files) {
    const pkg = file.package || "";

    // Process api.v1 and shared.v1 packages
    if (!pkg.startsWith("api.v1") && !pkg.startsWith("shared.v1")) continue;

    const comments = buildCommentMap(file.sourceCodeInfo?.location || []);

    // Parse top-level messages (field 4 = message_type)
    (file.messageType || []).forEach((msg, msgIdx) => {
      parseMessage(msg, pkg, "", comments, `4.${msgIdx}`, messages, enums);
    });

    // Parse top-level enums (field 5 = enum_type)
    (file.enumType || []).forEach((enumDesc, enumIdx) => {
      const fullName = `${pkg}.${enumDesc.name}`;
      const description = comments.get(`5.${enumIdx}`) || "";
      const values = (enumDesc.value || []).map((v, vIdx) => ({
        name: v.name,
        number: v.number || 0,
        description: comments.get(`5.${enumIdx}.2.${vIdx}`) || "",
      }));
      enums[fullName] = { name: enumDesc.name, fullName, description, values };
    });

    // Parse services (field 6 = service)
    (file.service || []).forEach((svc, svcIdx) => {
      const fullName = `${pkg}.${svc.name}`;
      const description = comments.get(`6.${svcIdx}`) || "";

      const methods: MethodInfo[] = (svc.method || []).map((m, methodIdx) => {
        const inputType = (m.inputType || "").replace(/^\./, "");
        const outputType = (m.outputType || "").replace(/^\./, "");
        const methodDesc = comments.get(`6.${svcIdx}.2.${methodIdx}`) || "";

        return {
          name: m.name,
          description: methodDesc,
          httpPath: `/${fullName}/${m.name}`,
          options: extractMethodOptions(m.options),
          inputType,
          outputType,
        };
      });

      services.push({ name: svc.name, fullName, description, methods });
    });
  }

  return {
    version: "1.0",
    generatedAt: new Date().toISOString(),
    services,
    messages,
    enums,
  };
}

// ── Entry point ──
const descriptorPath = join(__dirname, "..", "public", "api-data", "descriptor.json");
const outputPath = join(__dirname, "..", "public", "api-data", "api.json");

mkdirSync(join(__dirname, "..", "public", "api-data"), { recursive: true });

console.log(`Reading descriptor from ${descriptorPath}`);
const apiData = parseDescriptor(descriptorPath);

console.log(
  `Found ${apiData.services.length} services, ` +
    `${Object.keys(apiData.messages).length} messages, ` +
    `${Object.keys(apiData.enums).length} enums`,
);

// Log stats
let methodsWithOptions = 0;
let sensitiveFields = 0;
let descriptionsCount = 0;
for (const svc of apiData.services) {
  if (svc.description) descriptionsCount++;
  for (const m of svc.methods) {
    if (m.options.agentOnly || m.options.userOnly || m.options.skipAuth) methodsWithOptions++;
    if (m.description) descriptionsCount++;
  }
}
for (const msg of Object.values(apiData.messages)) {
  if (msg.description) descriptionsCount++;
  for (const f of msg.fields) {
    if (f.sensitive) sensitiveFields++;
    if (f.description) descriptionsCount++;
  }
}
for (const e of Object.values(apiData.enums)) {
  if (e.description) descriptionsCount++;
  for (const v of e.values) {
    if (v.description) descriptionsCount++;
  }
}
console.log(`Methods with custom options: ${methodsWithOptions}`);
console.log(`Sensitive fields: ${sensitiveFields}`);
console.log(`Total descriptions: ${descriptionsCount}`);

writeFileSync(outputPath, JSON.stringify(apiData, null, 2));
console.log(`Written to ${outputPath}`);
